version: "3.7"

services:
  app:
    container_name: express-app
    restart: always
    image: truji96/wize-adrian-trujillo:latest
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}